server:
  port: 8005
spring:
  application:
    name: edu-comment-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.17.129:3306/edu_comment?useUnicode=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: Hhc000410.
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true