server:
  port: 9001
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: edu-gateway-boot
  cloud:
    gateway:
      routes:
        - id: edu-routes-ad # 路由名
          uri: lb://edu-ad-boot # 去注册中心查找的微服务名
          predicates: # 当断言成功后，交给某一个微服务处理时使用的是 转发
            - Path=/ad/**
          filters:
            - StripPrefix=1 # 去掉 uri 的第一部分
        - id: edu-routes-userSetting
          uri: lb://edu-user-boot
          predicates:
            - Path=/userSetting/**
        - id: edu-routes-course
          uri: lb://edu-course-boot
          predicates:
            - Path=/course/**
          filters:
            - StripPrefix=1
        - id: edu-routes-comment
          uri: lb://edu-comment-boot
          predicates:
            - Path=/comment/**